// login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
// registration
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const UPLOAD_LOGO_IMAGE = "UPLOAD_LOGO_IMAGE";
export const UPLOAD_FAIL="UPLOAD_FAIL"
export const REGISTER_FAIL = "REGISTER_FAIL";
export const EMAIL_VERIFY_SUCCESS = "EMAIL_VERIFY_SUCCESS"
export const RESET_PASSWORD="RESET_PASSWORD";
export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST";



