// login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
// registration
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const UPLOAD_LOGO_IMAGE = "UPLOAD_LOGO_IMAGE";
export const UPLOAD_FAIL="UPLOAD_FAIL"
export const REGISTER_FAIL = "REGISTER_FAIL";
export const EMAIL_VERIFY_SUCCESS = "EMAIL_VERIFY_SUCCESS"
export const RESET_PASSWORD="RESET_PASSWORD";
export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST";
// update
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

// address
export const GET_REGISTER_ADDRESS = "GET_REGISTER_ADDRESS";
export const CLEAR_REGISTER_ADDRESS = "CLEAR_REGISTER_ADDRESS";
export const GET_BROKERAGE_ADDRESS = "GET_BROKERAGE_ADDRESS";
export const CLEAR_BROKERAGE_ADDRESS = "CLEAR_BROKERAGE_ADDRESS";
export const GET_UPDATE_PROFILE_ADDRESS = "GET_UPDATE_PROFILE_ADDRESS";
export const CLEAR_UPDATE_PROFILE_ADDRESS = "CLEAR_UPDATE_PROFILE_ADDRESS";





