export const GET_AGENT_OPTIONS = "GET_AGENT_OPTIONS";
export const GET_BROKERAGES_OPTIONS = "GET_BROKERAGES_OPTIONS";
export const ADD_BROKERAGE = "ADD_BROKERAGE";
export const GET_BROKERAGES_LIST = "GET_BROKERAGES_LIST";
export const GET_LINKED_ACCOUNTS_LIST = "GET_LINKED_ACCOUNTS_LIST";

